/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.admin.job_statuses;

import Models.job_status;
import Renders.Table.Tabla;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucia Tortosa
 */
public class index extends javax.swing.JFrame {

    Tabla t = new Tabla();

    String table = "medical_records";

    ArrayList<String> nombreArrayList = new ArrayList<String>();

    Controllers.job_statuses controller;

    /**
     * Creates new form index
     */
    public index() {
        initComponents();

        controller = new Controllers.job_statuses();

        t.ver_tabla(tabla, controller.header, controller.get_Data());

        add_button.setBorderPainted(false);
        add_button.setFocusPainted(false);
        add_button.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        add_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estados civiles");
        setMinimumSize(new java.awt.Dimension(760, 572));
        setSize(new java.awt.Dimension(746, 535));
        getContentPane().setLayout(null);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 30, 740, 470);

        jPanel5.setBackground(new java.awt.Color(224, 232, 231));

        add_button.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        add_button.setForeground(new java.awt.Color(51, 51, 255));
        add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        add_button.setText("Añadir nuevo registro");
        add_button.setToolTipText("");
        add_button.setBorder(null);
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 575, Short.MAX_VALUE)
                .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(add_button)
                .addContainerGap())
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(3, 490, 735, 40);

        jLabel2.setBackground(new java.awt.Color(0, 110, 212));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Situación laboral");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 17));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 17));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 17));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(3, 3, 735, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        form frame = new form(null, this, -1);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_add_buttonActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked

        int column = tabla.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tabla.getRowHeight();

        if (row < tabla.getRowCount() && row >= 0 && column < tabla.getColumnCount() && column >= 0) {
            Object value = tabla.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                if (boton.getName().equals("d")) {
                    job_status m = controller.getModel(row);
                    Object[] options = {"Aceptar", "Cancelar"};
                    int n = JOptionPane.showOptionDialog(this, "Desea eliminar el registro: " + m.getName() + "?",
                            "Eliminar registro",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.ERROR_MESSAGE,
                            null,
                            options,
                            options[0]);
                    if (n == 0) {
                        controller.delete(m.getId());
                        controller.list.remove(row);

                        ((DefaultTableModel) tabla.getModel()).removeRow(row);
                    }
                } else {
                    if (boton.getName().equals("m")) {
                        Models.job_status model = controller.getModel(row);
                        form frame = new form(model, this, row);
                        frame.setLocationRelativeTo(null);
                        frame.setVisible(true);
                        this.setEnabled(false);
                    }
                    if (boton.getName().equals("s")) {
                        Models.job_status model = controller.getModel(row);
                        show frame = new show(model, this);
                        frame.setLocationRelativeTo(null);
                        frame.setVisible(true);
                        this.setEnabled(false);
                    }
                }
            }
        }
    }//GEN-LAST:event_tablaMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton add_button;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
