/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.medical_records;

import DB.SQLiteJDBC;
import Models.medical_record;
import Renders.Buttons.Button;
import Renders.Table.Tabla;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Lucia Tortosa
 */
public class index extends javax.swing.JFrame {

    Tabla t = new Tabla();
    private Boolean subtable_open = false;
    private subtable sub;
    private int subtable_index;
    Controllers.medical_records controller;

    /**
     * Creates new form index
     */
    public index() {
        initComponents();

        controller = new Controllers.medical_records();

        t.ver_tabla(tabla, controller.header, controller.get_Data());

        add_button.setBorderPainted(false);
        add_button.setFocusPainted(false);
        add_button.setContentAreaFilled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        add_button = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(650, 500));
        setPreferredSize(new java.awt.Dimension(746, 535));
        setSize(new java.awt.Dimension(746, 535));
        getContentPane().setLayout(null);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 70, 740, 510);

        jPanel5.setBackground(new java.awt.Color(194, 227, 226));

        add_button.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        add_button.setForeground(new java.awt.Color(51, 51, 255));
        add_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        add_button.setText("Añadir nuevo registro");
        add_button.setToolTipText("");
        add_button.setBorder(null);
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 590, Short.MAX_VALUE)
                .addComponent(add_button, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(add_button)
                .addContainerGap())
        );

        getContentPane().add(jPanel5);
        jPanel5.setBounds(-5, 570, 750, 50);

        jLabel2.setBackground(new java.awt.Color(0, 102, 102));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("EXPEDIENTES");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 17));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 17));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 17));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(3, 3, 740, 80);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        Views.medical_records.form frame = new Views.medical_records.form(null, this, -1);
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
    }//GEN-LAST:event_add_buttonActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked

        int column = tabla.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / tabla.getRowHeight();

        if (row < tabla.getRowCount() && row >= 0 && column < tabla.getColumnCount() && column >= 0) {
            Object value = tabla.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;

                if (boton.getName().equals("+")) {
                    if (subtable_open) {
                        subtable_hide();
                        row -= 10;
                    }
                    subtable_index = row;
                    Button btn = new Button();
                    DefaultTableModel model = (DefaultTableModel) tabla.getModel();
                    model.setValueAt(btn.getButton("-"), row, 0);
                    Object rowData[] = {"", "", "", "", "", "", "", ""};
                    for (int x = 0; x <= 9; x++) {
                        model.insertRow(row + 1, rowData);
                    }
                    subtable_open = true;
                    sub = new subtable(controller.getModel(row).getId());
                    sub.setBounds(0, (row + 1) * 30, 750, 300);
                    tabla.add(sub);
                    
                    
                }

                if (boton.getName().equals("m")) {
                    Models.medical_record model = controller.getModel(row);
                    form frame = new form(model, this, row);
                    frame.setLocationRelativeTo(null);
                    frame.setVisible(true);
                    this.setEnabled(false);
                }

                if (boton.getName().equals("d")) {
                    medical_record m = controller.getModel(row);
                    Object[] options = {"Aceptar", "Cancelar"};
                    int n = JOptionPane.showOptionDialog(this, "Desea eliminar el registro: " + m.getName() + "?",
                            "Eliminar registro",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.ERROR_MESSAGE,
                            null,
                            options,
                            options[0]);
                    if (n == 0) {
                        controller.delete(m.getId());
                        controller.list.remove(row);

                        ((DefaultTableModel) tabla.getModel()).removeRow(row);
                    }
                }

                if (boton.getName().equals("-")) {
                    subtable_open = false;
                    subtable_hide();
                    Button btn = new Button();
                    DefaultTableModel model = (DefaultTableModel) tabla.getModel();
                    model.setValueAt(btn.getButton("+"), row, 0);
                }
            }
        }
    }//GEN-LAST:event_tablaMouseClicked

    private void subtable_hide() {
        DefaultTableModel model = (DefaultTableModel) tabla.getModel();
        Button btn = new Button();
        model.setValueAt(btn.getButton("+"), subtable_index, 0);
        for (int x = 0; x <= 9; x++) {
            model.removeRow(subtable_index + 1);
        }
        tabla.remove(sub);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_button;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
