/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.medical_records;

import Models.medical_record;
import Renders.Subtable.Tabla;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lucia Tortosa
 */
public class subtable extends javax.swing.JPanel {

    Tabla t = new Tabla();
    public Controllers.individual_reports controller_report;
    public Controllers.odat_diagnoses controller_odat;
    public int medical_record;

    /**
     * Creates new form subtable
     */
    public subtable(int medical_record) {
        this.medical_record = medical_record;

        initComponents();

        controller_report = new Controllers.individual_reports(medical_record);
        controller_odat = new Controllers.odat_diagnoses(medical_record);

        t.ver_tabla(subtabla_i, controller_report.header, controller_report.get_Data());
        t.ver_tabla(subtabla_d, controller_odat.header, controller_odat.get_Data());

        btn_add_diagnoses.setBorderPainted(false);
        btn_add_diagnoses.setFocusPainted(false);
        btn_add_diagnoses.setContentAreaFilled(false);

        btn_add_reports.setBorderPainted(false);
        btn_add_reports.setFocusPainted(false);
        btn_add_reports.setContentAreaFilled(false);

        subtabla_d.setName("subtable");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        subtabla_d = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        subtabla_i = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btn_add_diagnoses = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        btn_add_reports = new javax.swing.JButton();

        setBackground(new java.awt.Color(235, 241, 245));
        setLayout(null);

        subtabla_d.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        subtabla_d.getTableHeader().setReorderingAllowed(false);
        subtabla_d.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subtabla_dMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(subtabla_d);

        add(jScrollPane1);
        jScrollPane1.setBounds(30, 30, 600, 100);

        subtabla_i.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        subtabla_i.getTableHeader().setReorderingAllowed(false);
        subtabla_i.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                subtabla_iMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(subtabla_i);

        add(jScrollPane3);
        jScrollPane3.setBounds(30, 180, 600, 100);

        jLabel2.setBackground(new java.awt.Color(18, 77, 214));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("INFORMES");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setMaximumSize(new java.awt.Dimension(100, 17));
        jLabel2.setMinimumSize(new java.awt.Dimension(100, 17));
        jLabel2.setOpaque(true);
        jLabel2.setPreferredSize(new java.awt.Dimension(100, 17));
        add(jLabel2);
        jLabel2.setBounds(30, 152, 600, 30);

        jPanel5.setBackground(new java.awt.Color(194, 227, 241));

        btn_add_diagnoses.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btn_add_diagnoses.setForeground(new java.awt.Color(51, 51, 255));
        btn_add_diagnoses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btn_add_diagnoses.setText("Añadir nuevo registro");
        btn_add_diagnoses.setToolTipText("");
        btn_add_diagnoses.setBorder(null);
        btn_add_diagnoses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_diagnosesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 440, Short.MAX_VALUE)
                .addComponent(btn_add_diagnoses, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btn_add_diagnoses)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        add(jPanel5);
        jPanel5.setBounds(30, 128, 600, 30);

        jLabel3.setBackground(new java.awt.Color(18, 77, 214));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("DIAGNÓSTICOS");
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setMaximumSize(new java.awt.Dimension(100, 17));
        jLabel3.setMinimumSize(new java.awt.Dimension(100, 17));
        jLabel3.setOpaque(true);
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 17));
        add(jLabel3);
        jLabel3.setBounds(30, 0, 600, 33);

        jPanel6.setBackground(new java.awt.Color(211, 231, 241));

        btn_add_reports.setFont(new java.awt.Font("Tahoma", 3, 11)); // NOI18N
        btn_add_reports.setForeground(new java.awt.Color(51, 51, 255));
        btn_add_reports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btn_add_reports.setText("Añadir nuevo registro");
        btn_add_reports.setToolTipText("");
        btn_add_reports.setBorder(null);
        btn_add_reports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_add_reportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 440, Short.MAX_VALUE)
                .addComponent(btn_add_reports, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btn_add_reports))
        );

        add(jPanel6);
        jPanel6.setBounds(30, 280, 600, 23);
    }// </editor-fold>//GEN-END:initComponents

    private void subtabla_dMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtabla_dMouseClicked

        int column = subtabla_d.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / subtabla_d.getRowHeight();

        if (row < subtabla_d.getRowCount() && row >= 0 && column < subtabla_d.getColumnCount() && column >= 0) {
            Object value = subtabla_d.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                Models.odat_diagnose m = controller_odat.getModel(row);
                if (boton.getName().equals("m")) {
                    Views.odat_diagnoses.form frame = new Views.odat_diagnoses.form(m, this, row, medical_record);
                    frame.setVisible(true);
                }
                if (boton.getName().equals("d")) {
                    Object[] options = {"Aceptar", "Cancelar"};
                int n = JOptionPane.showOptionDialog(this, "Desea eliminar el informe con fecha: " + subtabla_d.getModel().getValueAt(row, 0) + "?",
                        "Eliminar registro",
                        JOptionPane.YES_NO_OPTION,
                        JOptionPane.ERROR_MESSAGE,
                        null,
                        options,
                        options[0]);
                if (n == 0) {
                    controller_odat.delete(m.getId());
                    controller_odat.list.remove(row);

                    ((DefaultTableModel) subtabla_d.getModel()).removeRow(row);
                }
                }
            }
        }
    }//GEN-LAST:event_subtabla_dMouseClicked

    private void subtabla_iMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subtabla_iMouseClicked

        int column = subtabla_i.getColumnModel().getColumnIndexAtX(evt.getX());
        int row = evt.getY() / subtabla_i.getRowHeight();

        if (row < subtabla_i.getRowCount() && row >= 0 && column < subtabla_i.getColumnCount() && column >= 0) {
            Object value = subtabla_i.getValueAt(row, column);
            if (value instanceof JButton) {
                ((JButton) value).doClick();
                JButton boton = (JButton) value;
                Models.individual_report m = controller_report.getModel(row);
                if (boton.getName().equals("m")) {
                    Views.individual_reports.form frame = new Views.individual_reports.form(m, this, row, medical_record);
                    frame.setVisible(true);
                }
                if (boton.getName().equals("d")) {
                    Object[] options = {"Aceptar", "Cancelar"};
                    int n = JOptionPane.showOptionDialog(this, "Desea eliminar el informe con fecha: " + subtabla_i.getModel().getValueAt(row, 0) + "?",
                            "Eliminar registro",
                            JOptionPane.YES_NO_OPTION,
                            JOptionPane.ERROR_MESSAGE,
                            null,
                            options,
                            options[0]);
                    if (n == 0) {
                        controller_report.delete(m.getId());
                        controller_report.list.remove(row);

                        ((DefaultTableModel) subtabla_i.getModel()).removeRow(row);
                    }
                }

            }
        }
    }//GEN-LAST:event_subtabla_iMouseClicked

    private void btn_add_diagnosesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_diagnosesActionPerformed
        Views.odat_diagnoses.form frame = new Views.odat_diagnoses.form(null, this, -1, medical_record);
        frame.setVisible(true);
    }//GEN-LAST:event_btn_add_diagnosesActionPerformed

    private void btn_add_reportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_add_reportsActionPerformed
        Views.individual_reports.form frame = new Views.individual_reports.form(null, this, -1, medical_record);
        frame.setVisible(true);
    }//GEN-LAST:event_btn_add_reportsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btn_add_diagnoses;
    public javax.swing.JButton btn_add_reports;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTable subtabla_d;
    public javax.swing.JTable subtabla_i;
    // End of variables declaration//GEN-END:variables
}
